/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ch.zhaw.paaq.api;

import ch.zhaw.paaq.model.Sensor;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-11-10T15:30:58.573456300+01:00[Europe/Berlin]")
@Validated
@Api(value = "sensors", description = "the sensors API")
public interface SensorsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /sensors
     * create new sensor in the database
     *
     * @param sensor  (optional)
     * @return successfully created a new sensor (status code 200)
     *         or bad input parameter (status code 400)
     */
    @ApiOperation(value = "", nickname = "addSensor", notes = "create new sensor in the database", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successfully created a new sensor"),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/sensors",
        consumes = { "application/json" }
    )
    default ResponseEntity<Void> addSensor(@ApiParam(value = "") @Valid @RequestBody(required = false) Sensor sensor) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /sensors/{entityId}/
     * change property of sensor
     *
     * @param entityId  (required)
     * @param sensor  (optional)
     * @return successfully changed property of sensor (status code 200)
     */
    @ApiOperation(value = "", nickname = "changeSensor", notes = "change property of sensor", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successfully changed property of sensor") })
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/sensors/{entityId}/"
    )
    default ResponseEntity<Void> changeSensor(@ApiParam(value = "", required = true) @PathVariable("entityId") String entityId,@ApiParam(value = "") @Valid Sensor sensor) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /sensors
     * get a list of sensors
     *
     * @return search results matching criteria (status code 200)
     *         or no entries (status code 204)
     *         or bad input parameter (status code 400)
     */
    @ApiOperation(value = "", nickname = "sensorsGet", notes = "get a list of sensors", response = Sensor.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "search results matching criteria", response = Sensor.class, responseContainer = "List"),
        @ApiResponse(code = 204, message = "no entries"),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/sensors",
        produces = { "application/json" }
    )
    default ResponseEntity<List<Sensor>> sensorsGet() {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"deviceType\" : \"O\", \"alarmUpperLimit\" : 0, \"startingPos\" : 0, \"dataType\" : \"float\", \"length\" : 2, \"alaramActive\" : 0, \"serial_port\" : \"/dev/ttyUSB0\", \"serialNrDevice\" : \"12770000001\", \"unit\" : \"%\", \"alarmLowerLimit\" : 0, \"system\" : \"Aqualab\", \"name\" : \"A_O2 % Sat\", \"id\" : 55, \"tank\" : \"A\", \"modBusPort\" : 10 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
