/**
 * Aquaponic Sensors DB API
 * An API to manage the sensors in the Aquaponic system
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: akcaden1@students.zhaw.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


 export interface Log { 
    id?: number;
    name: string;
    serialNrDevice: string;
    value: number;
    unit: string;
    tank: string;
    system: string;
    timestamp: string;
}

